
title: not_a_coder_blog
author: Shafqat Ullah Khan
email: iamshafqatkhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is for ReactJS, React Native Developers
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Shasikhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
